name: Test Orchestrator

# Allows a “Run workflow” button in the Actions tab
on:
  workflow_dispatch: {}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger tests in Repo 
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_PAT }}
          repository: JeffCompasClassrooms/testing-units-f25-jcnaef
          event-type: run-tests
      # ---- Repository 2 ----
      - name: Trigger tests in Repo 2
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_PAT }}
          repository: se3150/f24-testing-behaviors-jcnaef 
          event-type: run-tests

      # ---- Repository 3 ----
      - name: Trigger tests in Repo 3
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_PAT }}
          repository:JeffCompasClassrooms/testing-systems-jcnaef
          event-type: run-tests


